spring.application.name=auth-service
server.port=8081

#Base de datos propia del auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/chat_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#JWT
jwt.secret=&Q9BH7RyQC[GL7$=Azc%zq?#kwGTbm8$
jwt.expiration-minutes=120