spring.application.name=bot-service
server.port=8083

# Base de datos propia del bot-service
spring.datasource.url=jdbc:mysql://localhost:3306/chat_bot_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Debe ser la MISMA clave del auth-service y chat-service
jwt.secret=&Q9BH7RyQC[GL7$=Azc%zq?#kwGTbm8$

# API externa gratuita
jikan.api.base-url=https://api.jikan.moe/v4