spring.application.name=bot-service
server.port=${PORT:8083}

spring.datasource.url=${BOT_DB_URL:jdbc:mysql://localhost:3306/chat_bot_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${RAILWAY_PRIVATE_DOMAIN:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=${PORT:8083}

jwt.secret=${JWT_SECRET:clave_local_de_desarrollo_minimo_32_caracteres}

jikan.api.base-url=${JIKAN_API_BASE_URL:https://api.jikan.moe/v4}