spring.application.name=chat-service

server.port=8082

# Base de datos propia del chat-service
spring.datasource.url=jdbc:mysql://localhost:3306/chat_messages_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Debe ser la MISMA clave usada en auth-service
jwt.secret=&Q9BH7RyQC[GL7$=Azc%zq?#kwGTbm8$
